name: Deployment pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]
        types: [opened, synchronize]

jobs:
    backend:
        runs-on: ubuntu-20.04
        defaults:
            run:
                working-directory: ./bloglist-backend
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: '20'
            - name: Install dependencies
              run: npm install
            - name: Lint
              run: npm run lint
            - name: Test
              run: npm test
    frontend:
        runs-on: ubuntu-20.04
        defaults:
            run:
                working-directory: ./bloglist-frontend
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: '20'
            - name: Install dependencies
              run: npm install
            - name: Lint
              run: npm run lint
